# stage 1 - Build

FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Stage 2 - Distroless

FROM gcr.io/distroless/nodejs20-debian13

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["./node_modules/.bin/serve", "-s", "dist", "-l", "3000"]
